## TENSORFLOW 2.0

In [3]:
#This is to show the basic functionality of keras and tf

import tensorflow as tf
a=tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
b=tf.constant(3)
b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
#apparently tf 2.0 doesnt support session anymore
sess=tf.Session()
sess.run(c)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [11]:
a=tf.constant([[3,3],[3,3]])
b=tf.constant([[3,3],[3,3]])
c=tf.matmul(a,b)

In [12]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 18],
       [18, 18]])>

In [13]:
import os

In [14]:
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [22]:
#initialisation of tensors
x=tf.constant(4)
y=tf.constant(4.0)
z=tf.constant(4, shape=(1,1),dtype=tf.float32) #specifying shape and dtype
x=tf.constant([[1,2,3],[4,5,6]])
a=tf.ones((3,3))
print(a)
print(x,y)
print(z)
b=tf.eye(3)#eye for identity matrix
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [23]:
x=tf.random.normal((3,3),mean=0, stddev=1) #so this is from a standard normal distr.
print(x)

tf.Tensor(
[[-1.8763626  -0.19023617  1.0844334 ]
 [ 0.25797367  0.54109454  1.0103608 ]
 [-2.617901   -0.4739381  -0.04223541]], shape=(3, 3), dtype=float32)


In [24]:
x=tf.random.uniform((1,3),minval=0, maxval=1) #so this is from a standard uniform distr.
print(x)

tf.Tensor([[0.8141377  0.18488467 0.346259  ]], shape=(1, 3), dtype=float32)


In [26]:
x=tf.range(start=1, limit=11,delta=2) #delta is the step size , we can also init the range func normally 
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [27]:
tf.cast(x, dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [29]:
#Mathematical operations
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [31]:
z=tf.subtract(y,x)
z=y-x
print(z)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)


In [32]:
z=tf.divide(y,x)
print(z)

tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)


In [33]:
z=tf.multiply(x,y)
z=x*y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [36]:
z=tf.tensordot(x,y, axes=1) #element wise mult and summation
print(z)
z=tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [37]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[ 0.75067115 -0.9535808   0.30721915 -0.35952115]
 [ 0.30280447  0.32290393 -0.10761511  0.22533263]], shape=(2, 4), dtype=float32)


In [42]:
x=tf.constant(range(10))
print(x[:])
print(x[1:3])
print(x[::3])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 3 6 9], shape=(4,), dtype=int32)


In [43]:
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [45]:
x=tf.constant([[1,2],
             [3,4],
             [5,6]])
print(x[0,:])
print(x)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [50]:
#reshaping
x=tf.range(9)
print(x)
x=tf.reshape(x,(3,3))
print(x)
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
